Repository tomezpl/sth-gamemode, pull requests merged in 2025-02, with the labels that each got.

#93 feat(client): added ability to hold enter control to enter vehicles as passenger
  src/SurviveTheHuntClient/Helpers/PlayerPassenger.cs
  src/SurviveTheHuntClient/MainScript.cs
  src/SurviveTheHuntClient/SurviveTheHuntClient.csproj
Labels: game-design

#98 feat(client/ui): added a "help & tips" submenu
  .github/workflows/shared-create-release.yml
  src/SurviveTheHuntClient.UI/MainScript.cs
  src/SurviveTheHuntClient.UI/SurviveTheHuntClient.UI.csproj
  ui_files/appearance.png
  ui_files/bus.png
  ui_files/lslimits.png
  uimanifest.lua
Labels: ui

#99 feat(client): allows hunted player to driveby as passenger
  src/SurviveTheHuntClient/MainScript.cs
  src/SurviveTheHuntClient/PlayerState.cs
Labels: game-design

#100 feat(client): added a "wasted" visual & audio effect on player death
  src/SurviveTheHuntClient/Helpers/KillTracker.cs
  src/SurviveTheHuntClient/Helpers/WastedAnim.cs
  src/SurviveTheHuntClient/MainScript.cs
  src/SurviveTheHuntClient/SurviveTheHuntClient.csproj
Labels: enhancement

#102 Update vehicles.json
  configs/vehicles.json
Labels: enhancement, priority: low
